name = "protocol-app"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "protocol-videos"

